#!/bin/bash

OPTSTRING=":p:s:o:"
unset -v project
unset -v stack
unset -v options
source ./project.conf

while getopts ${OPTSTRING} opt; do
  case ${opt} in
    p)
      #echo "Option -p was triggered, Argument: ${OPTARG}"
      project=${OPTARG}
      if [ $project == "all" ];then
        echo
      else
        cd ${OPTARG}
      fi
      ;;
    s)
      stack=${OPTARG}
      if [ $project == "all" ];then
          for prj in $projects
          do
            cd $prj
            pulumi stack select ${OPTARG}
            cd ..
          done
      else
        pulumi stack select ${OPTARG}
      fi
      ;;
    o)
      #echo "Option -o was triggered, run: pulumi ${OPTARG}"
      options=${OPTARG}
      if [ "$project" == "all" ];then
          for prj in $projects
          do
            echo "Project: $prj"
            cd $prj
            pulumi $options
            cd ..
          done
      else
          pulumi $options
      fi
      ;;
    :)
      echo "Option -${OPTARG} requires an argument."
      echo "Usage: pulumi-orch -p <$projects> -s <$stacks>  -o <pulumi args>"
      exit 1
      ;;
    ?)
      echo "Invalid option: -${OPTARG}."
      echo "Usage: pulumi-orch -p <$projects> -s <$stacks>  -o <pulumi args>"
      exit 1
      ;;
  esac
done
shift "$(( OPTIND - 1 ))"

if [ -z "$project" ] || [ -z "$stack" ] || [ -z "$options" ]; then
        echo 'Missing either of the flags -p or -s or -o' >&2
        exit 1
fi

